# -*- coding: utf-8 -*-
"""1-71-app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAKX3cLgSzfr2IlyWEeL4jgrcWyeajOe
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-10 ,10 , 10000 )

y1 = np.tanh(0*x) -2/x +1
y2 = np.tanh(0.1*x) -2/x +1
y3 = np.tanh(0.2*x) -2/x +1
y4= np.tanh(0.4*x) -2/x +1
y5= np.tanh(0.6*x) -2/x +1
y6= np.tanh(1*x) -2/x +1
y7= np.tanh(3*x) -2/x +1

plt.style.use('seaborn-darkgrid')

plt.figure(figsize=(18,11))
plt.grid(alpha = 0.5 , color = 'gray' , linestyle = '-' , linewidth = '0.7')


plt.plot(x , y1 , label = '$a=0$')
plt.plot(x , y2 , label = '$a=0.1$')
plt.plot(x , y3 , label = '$a=0.2$')
plt.plot(x , y4 , label = '$a=0.4$')
plt.plot(x , y5 , label = '$a=0.6$')
plt.plot(x , y6 , label = '$a=1$')
plt.plot(x , y7 , label = '$a=3$')


plt.xlim(-0.5, 2.5)
plt.ylim(-1 , 1)

plt.axhline(y=0 , xmin =-10 , xmax =10 , color = 'black')
plt.axvline(x=0 , ymin =-10 , ymax =10 , color = 'black')

plt.legend(loc = "upper left" , prop={'size':21.8})

plt.title('Soluciones de $\kappa$ para diferentes valores de $a$' , fontsize = 25 , )
plt.xlabel('$\kappa$' , fontsize = 25)
plt.ylabel('$f(\kappa)$ ' , fontsize = 25)

plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)

plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)

plt.savefig('1-71-valoresa-app.png')

plt.show()

a = [0.00000000    ,   5.00000007E-02,  0.100000001    ,  0.150000006    ,  0.200000003    ,  0.250000000    ,  0.300000012    ,  0.350000024    ,  0.400000036    ,  0.450000048    ,  0.500000060    ,  0.550000072    ,  0.600000083    ,  0.650000095    ,  0.700000107    ,  0.750000119    ,  0.800000131    ,  0.850000143    ,  0.900000155    ,  0.950000167    ,   1.00000012    ,   1.05000007    ,   1.10000002    ,   1.14999998    ,   1.19999993    ,   1.24999988    ,   1.29999983    ,   1.34999979    ,   1.39999974    ,   1.44999969    ,   1.49999964    ,   1.54999959    ,   1.59999955    ,   1.64999950    ,   1.69999945    ,   1.74999940    ,   1.79999936    ,   1.84999931    ,   1.89999926    ,   1.94999921    ,   1.99999917    ,   2.04999924    ,   2.09999919    ,   2.14999914    ,   2.19999909    ,   2.24999905    ,   2.29999900    ,   2.34999895    ,   2.39999890    ,   2.44999886    ,   2.49999881    ,   2.54999876    ,   2.59999871    ,   2.64999866    ,   2.69999862    ,   2.74999857    ,   2.79999852    ,   2.84999847    ,   2.89999843    ,   2.94999838    ,   2.99999833    ,   3.04999828    ,   3.09999824    ,   3.14999819    ,   3.19999814    ,   3.24999809    ,   3.29999804    ,   3.34999800    ,   3.39999795    ,   3.44999790    ,   3.49999785    ,   3.54999781    ,   3.59999776    ,   3.64999771    ,   3.69999766    ,   3.74999762    ,   3.79999757    ,   3.84999752    ,   3.89999747    ,   3.94999743    ,   3.99999738    ,   4.04999733    ,   4.09999752    ,   4.14999771    ,   4.19999790    ,   4.24999809    ,   4.29999828    ,   4.34999847    ,   4.39999866    ,   4.44999886    ,   4.49999905    ,   4.54999924    ,   4.59999943    ,   4.64999962    ,   4.69999981    ,   4.75000000    ,   4.80000019    ,   4.85000038    ,   4.90000057    ,   4.95000076    ,   5.00000095]

e = [-2.00001526    ,  -1.67913377    ,  -1.46257031    ,  -1.30548942    ,  -1.18591893    ,  -1.09175253    ,  -1.01563215    , -0.952849090    , -0.900240123    , -0.855579913    , -0.817236722    , -0.784027636    , -0.755047143    , -0.729595363    , -0.707118094    , -0.687155247    , -0.669365942    , -0.653466105    , -0.639188528    , -0.626348853    , -0.614789486    , -0.604327142    , -0.594869554    , -0.586295962    , -0.578522980    , -0.571454167    , -0.565028787    , -0.559188306    , -0.553875864    , -0.549036443    , -0.544632196    , -0.540610552    , -0.536951602    , -0.533620358    , -0.530582368    , -0.527803838    , -0.525282800    , -0.522986233    , -0.520897210    , -0.518983305    , -0.517243624    , -0.515677333    , -0.514237225    , -0.512922704    , -0.511733413    , -0.510653377    , -0.509666920    , -0.508773804    , -0.507958353    , -0.507220387    , -0.506544411    , -0.505930245    , -0.505377829    , -0.504871726    , -0.504427195    , -0.504013479    , -0.503630519    , -0.503293693    , -0.502987564    , -0.502696812    , -0.502452016    , -0.502222598    , -0.502008557    , -0.501809776    , -0.501641691    , -0.501488864    , -0.501351297    , -0.501229107    , -0.501106858    , -0.500999928    , -0.500908315    , -0.500816703    , -0.500740349    , -0.500679255    , -0.500602901    , -0.500557125    , -0.500496030    , -0.500450253    , -0.500404418    , -0.500373900    , -0.500328124    , -0.500297606    , -0.500267088    , -0.500251830    , -0.500221252    , -0.500205994    , -0.500190735    , -0.500160217    , -0.500144958    , -0.500129700    , -0.500129700    , -0.500114441    , -0.500099182    , -0.500083923    , -0.500083923    , -0.500068665    , -0.500068665    , -0.500068665    , -0.500053406    , -0.500053406    , -0.500038147]

plt.style.use('seaborn-darkgrid')
plt.figure(figsize=(18,11))
plt.plot(a , e , color = 'red' , label = 'Energía')

plt.grid(alpha = 0.5 , color = 'gray' , linestyle = '-' , linewidth = '0.7')

plt.title('Energía en función de la semidistancia $a$' , fontsize = 25 )
plt.xlabel('$a$ $(a.u)$' , fontsize = 25 , color = 'black')
plt.ylabel('$E$ $(a.u)$ ' , fontsize = 25 , color = 'black')

plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)
plt.rc('lines', linewidth=3 , color='r')

plt.legend(loc = "upper left" , prop={'size':24})

plt.savefig('1-71-energia-app.png')

plt.show()

k = 1.10886383
a = 1
A2 = (a + (np.cosh(k*a))**2 / k  + (np.sinh(2*k*a)) / 2*k )

A = np.sqrt(A2)

x1 = np.linspace(-15 , -1 , 1000)
x2 = np.linspace(-1 , 1 , 1000)
x3 = np.linspace(1 , 15 , 1000)

y1 = A*np.cosh(k*a)*np.exp(k*(x1+a))
y2 = A*np.cosh(k*x2)
y3 = A*np.cosh(k*a)*np.exp(-k*(x3-a))

plt.figure(figsize=(18,11))

plt.plot(x1 , y1 , color = 'darkviolet' , label = '$\psi(x)$ $x<-a$')
plt.plot(x2 , y2 , color = 'crimson' ,label = '$\psi(x)$ $-a<x<a$' )
plt.plot(x3 , y3 , color = 'springgreen' , label = '$\psi(x)$ $x>a$')

plt.title('Función de onda en el espacio' , fontsize = 25 )
plt.xlabel('$x$ $(a.u)$' , fontsize = 25 , color = 'black')
plt.ylabel('$\psi(x)$ ' , fontsize = 25 , color = 'black')

plt.rc('lines', linewidth=2.3 , color='r')


plt.xlim(-5 , 5)

plt.legend(loc = "upper left" , prop={'size':23})

plt.savefig('1-71-funciononda-app.png')

plt.figure(figsize=(18,11))


plt.axhline(y=0 , xmin =-10 , xmax =10 , color = 'black')

plt.axhline(y=-0.592 , xmin =-10 , xmax =10 , color = 'orange' , label = 'Energia')


plt.axvline(x=-1 , ymin =-0.1 , ymax =0.5 , color = 'royalblue' , label = 'Potencial $V(x)$')
plt.axvline(x=1 , ymin =-0.1 , ymax =0.5 , color = 'royalblue')

plt.title('Potencial y energía para $a=1$ $a.u$' , fontsize = 25 )
plt.xlabel('$x$ $(a.u)$' , fontsize = 25 , color = 'black')
plt.ylabel('$V(x)$ ' , fontsize = 25 , color = 'black')

plt.xlim(-5 , 5)
plt.ylim(-4 , 4)

plt.legend(loc = "upper left" , prop={'size':23})

plt.savefig('1-71-potencialenergia-app.png')